package com.lfsolutions.retail.model.sale.order

import com.google.gson.annotations.SerializedName


data class SalesOrder (

  @SerializedName("id"                   ) var id                   : String?  = null,
  @SerializedName("soNo"                 ) var soNo                 : String?  = null,
  @SerializedName("soDate"               ) var soDate               : String?  = null,
  @SerializedName("locationId"           ) var locationId           : Int?     = null,
  @SerializedName("erpInternalId"        ) var erpInternalId        : String?  = null,
  @SerializedName("deliveryDate"         ) var deliveryDate         : String?  = null,
  @SerializedName("customerId"           ) var customerId           : String?  = null,
  @SerializedName("memberId"             ) var memberId             : String?  = null,
  @SerializedName("customerName"         ) var customerName         : String?  = null,
  @SerializedName("isCancelled"          ) var isCancelled          : Boolean? = null,
  @SerializedName("poNo"                 ) var poNo                 : String?  = null,
  @SerializedName("soItemDiscount"       ) var soItemDiscount       : String?  = null,
  @SerializedName("soNetDiscountPerc"    ) var soNetDiscountPerc    : String?  = null,
  @SerializedName("soNetDiscount"        ) var soNetDiscount        : Int?     = null,
  @SerializedName("soSubTotal"           ) var soSubTotal           : String?  = null,
  @SerializedName("soTax"                ) var soTax                : String?  = null,
  @SerializedName("soNetTotal"           ) var soNetTotal           : String?  = null,
  @SerializedName("soRoundingAmount"     ) var soRoundingAmount     : Int?     = null,
  @SerializedName("otherCharges"         ) var otherCharges         : Int?     = null,
  @SerializedName("soGrandTotal"         ) var soGrandTotal         : String?  = null,
  @SerializedName("salespersonId"        ) var salespersonId        : Int?     = null,
  @SerializedName("deliveryPersonId"     ) var deliveryPersonId     : String?  = null,
  @SerializedName("employeeId"           ) var employeeId           : String?  = null,
  @SerializedName("soTotalValue"         ) var soTotalValue         : String?  = null,
  @SerializedName("profitMargin"         ) var profitMargin         : Int?     = null,
  @SerializedName("remarks"              ) var remarks              : String?  = null,
  @SerializedName("creditDays"           ) var creditDays           : Int?     = null,
  @SerializedName("status"               ) var status               : String?  = null,
  @SerializedName("salesOrderStatusId"   ) var salesOrderStatusId   : String?  = null,
  @SerializedName("paymentTermId"        ) var paymentTermId        : String?  = null,
  @SerializedName("tenantId"             ) var tenantId             : Int?     = null,
  @SerializedName("salesPersonName"      ) var salesPersonName      : String?  = null,
  @SerializedName("branchId"             ) var branchId             : String?  = null,
  @SerializedName("taxName"              ) var taxName              : String?  = null,
  @SerializedName("type"                 ) var type                 : String?  = null,
  @SerializedName("paidAmount"           ) var paidAmount           : Int?     = null,
  @SerializedName("balance"              ) var balance              : Int?     = null,
  @SerializedName("usedAmount"           ) var usedAmount           : Int?     = null,
  @SerializedName("fromLocationId"       ) var fromLocationId       : String?  = null,
  @SerializedName("salesInvoiceId"       ) var salesInvoiceId       : String?  = null,
  @SerializedName("employeeName"         ) var employeeName         : String?  = null,
  @SerializedName("fromLocationName"     ) var fromLocationName     : String?  = null,
  @SerializedName("orderedQty"           ) var orderedQty           : Int?     = null,
  @SerializedName("receivedQty"          ) var receivedQty          : Int?     = null,
  @SerializedName("balanceQty"           ) var balanceQty           : Int?     = null,
  @SerializedName("notified"             ) var notified             : Boolean? = null,
  @SerializedName("collected"            ) var collected            : Boolean? = null,
  @SerializedName("binLocation"          ) var binLocation          : String?  = null,
  @SerializedName("isAutoPayment"        ) var isAutoPayment        : Boolean? = null,
  @SerializedName("paymentReference"     ) var paymentReference     : String?  = null,
  @SerializedName("currencyId"           ) var currencyId           : String?  = null,
  @SerializedName("currencyRate"         ) var currencyRate         : Int?     = null,
  @SerializedName("isLuggageAccepted"    ) var isLuggageAccepted    : Boolean? = null,
  @SerializedName("module"               ) var module               : Int?     = null,
  @SerializedName("poQuantity"           ) var poQuantity           : Int?     = null,
  @SerializedName("orderedQuantity"      ) var orderedQuantity      : Int?     = null,
  @SerializedName("addOn"                ) var addOn                : String?  = null,
  @SerializedName("purchaseOrderId"      ) var purchaseOrderId      : String?  = null,
  @SerializedName("walkInCustomerDetail" ) var walkInCustomerDetail : String?  = null,
  @SerializedName("walkInCustomer"       ) var walkInCustomer       : String?  = null,
  @SerializedName("isDeleted"            ) var isDeleted            : Boolean? = null,
  @SerializedName("deleterUserId"        ) var deleterUserId        : String?  = null,
  @SerializedName("deletionTime"         ) var deletionTime         : String?  = null,
  @SerializedName("lastModificationTime" ) var lastModificationTime : String?  = null,
  @SerializedName("lastModifierUserId"   ) var lastModifierUserId   : String?  = null,
  @SerializedName("creationTime"         ) var creationTime         : String?  = null,
  @SerializedName("creatorUserId"        ) var creatorUserId        : String?  = null,
  @SerializedName("totalDiscountAmount"  ) var totalDiscountAmount  : Int?     = null,
  @SerializedName("totalShipmentCharges" ) var totalShipmentCharges : Int?     = null,
  @SerializedName("roundedAmount"        ) var roundedAmount        : Int?     = null,
  @SerializedName("localTotal"           ) var localTotal           : String?  = null,
  @SerializedName("isFoc"                ) var isFoc                : Boolean? = null,
)