package com.lfsolutions.retail.model.sale.order

import com.google.gson.annotations.SerializedName


data class SalesOrder(
    @SerializedName("Id") var Id: String? = null,
    @SerializedName("SoNo") var SoNo: String? = null,
    @SerializedName("SoDate") var SoDate: String? = null,
    @SerializedName("LocationId") var LocationId: Int? = 0,
    @SerializedName("ERPInternalId") var ERPInternalId: String? = null,
    @SerializedName("DeliveryDate") var DeliveryDate: String? = null,
    @SerializedName("CustomerId") var CustomerId: Int? = 0,
    @SerializedName("MemberId") var MemberId: String? = null,
    @SerializedName("CustomerName") var CustomerName: String? = null,
    @SerializedName("IsCancelled") var IsCancelled: Boolean? = null,
    @SerializedName("PoNo") var PoNo: String? = null,
    @SerializedName("SoItemDiscount") var SoItemDiscount: Double = 0.0,
    @SerializedName("SoNetDiscountPerc") var SoNetDiscountPerc: Double? = 0.0,
    @SerializedName("SoNetDiscount") var SoNetDiscount: Double = 0.0,
    @SerializedName("SoSubTotal") var SoSubTotal: Double = 0.0,
    @SerializedName("SoTax") var SoTax: Double = 0.0,
    @SerializedName("SoNetTotal") var SoNetTotal: Double = 0.0,
    @SerializedName("SoRoundingAmount") var SoRoundingAmount: Double = 0.0,
    @SerializedName("OtherCharges") var OtherCharges: Double = 0.0,
    @SerializedName("SoGrandTotal") var SoGrandTotal: Double? = 0.0,
    @SerializedName("SalespersonId") var SalespersonId: Int? = 0,
    @SerializedName("DeliveryPersonId") var DeliveryPersonId: String? = null,
    @SerializedName("EmployeeId") var EmployeeId: String? = null,
    @SerializedName("SoTotalValue") var SoTotalValue: Double = 0.0,
    @SerializedName("ProfitMargin") var ProfitMargin: Double? = null,
    @SerializedName("Remarks") var Remarks: String? = null,
    @SerializedName("CreditDays") var CreditDays: Int? = null,
    @SerializedName("Status") var Status: String? = "A",
    @SerializedName("SalesOrderStatusId") var SalesOrderStatusId: String? = null,
    @SerializedName("PaymentTermId") var PaymentTermId: Int? = null,
    @SerializedName("TenantId") var TenantId: Int? = null,
    @SerializedName("SalesPersonName") var SalesPersonName: String? = null,
    @SerializedName("BranchId") var BranchId: String? = null,
    @SerializedName("TaxName") var TaxName: String? = null,
    @SerializedName("Type") var Type: String? = null,
    @SerializedName("PaidAmount") var PaidAmount: Double = 0.0,
    @SerializedName("Balance") var Balance: Double = 0.0,
    @SerializedName("UsedAmount") var UsedAmount: Double = 0.0,
    @SerializedName("FromLocationId") var FromLocationId: String? = null,
    @SerializedName("SalesInvoiceId") var SalesInvoiceId: String? = null,
    @SerializedName("EmployeeName") var EmployeeName: String? = null,
    @SerializedName("FromLocationName") var FromLocationName: String? = null,
    @SerializedName("OrderedQty") var OrderedQty: Double? = null,
    @SerializedName("ReceivedQty") var ReceivedQty: Double? = null,
    @SerializedName("BalanceQty") var BalanceQty: Double? = null,
    @SerializedName("Notified") var Notified: Boolean? = null,
    @SerializedName("Collected") var Collected: Boolean? = null,
    @SerializedName("BinLocation") var BinLocation: String? = null,
    @SerializedName("IsAutoPayment") var IsAutoPayment: Boolean? = null,
    @SerializedName("PaymentReference") var PaymentReference: String? = null,
    @SerializedName("CurrencyId") var CurrencyId: String? = null,
    @SerializedName("CurrencyRate") var CurrencyRate: Double? = null,
    @SerializedName("IsLuggageAccepted") var IsLuggageAccepted: Boolean? = null,
    @SerializedName("Module") var Module: Int? = null,
    @SerializedName("POQuantity") var POQuantity: Double? = null,
    @SerializedName("OrderedQuantity") var OrderedQuantity: Double? = null,
    @SerializedName("AddOn") var AddOn: String? = null,
    @SerializedName("PurchaseOrderId") var PurchaseOrderId: String? = null,
    @SerializedName("WalkInCustomerDetail") var WalkInCustomerDetail: String? = null,
    @SerializedName("IsDeleted") var IsDeleted: Boolean? = null,
    @SerializedName("DeleterUserId") var DeleterUserId: String? = null,
    @SerializedName("DeletionTime") var DeletionTime: String? = null,
    @SerializedName("LastModificationTime") var LastModificationTime: String? = null,
    @SerializedName("LastModifierUserId") var LastModifierUserId: String? = null,
    @SerializedName("CreationTime") var CreationTime: String? = null,
    @SerializedName("CreatorUserId") var CreatorUserId: Int? = null,
    @SerializedName("Signature") var Signature: String? = null,
    @SerializedName("reportName") var reportName: String? = null,

    )