package com.lfsolutions.retail.model.sale.invoice

import com.google.gson.annotations.SerializedName


data class SalesInvoice(
    @SerializedName("Id") var Id: String? = null,
    @SerializedName("InvoiceNo") var InvoiceNo: String? = null,
    @SerializedName("InvoiceDate") var InvoiceDate: String? = null,
    @SerializedName("PoNo") var PoNo: String? = null,
    @SerializedName("LocationId") var LocationId: Int? = null,
    @SerializedName("CustomerId") var CustomerId: Int? = null,
    @SerializedName("CustomerName") var CustomerName: String? = null,
    @SerializedName("DeliveryTimingDescription") var DeliveryTimingDescription: String? = null,
    @SerializedName("CustomerRemarks") var CustomerRemarks: String? = null,
    @SerializedName("CompanyRemarks") var CompanyRemarks: String? = null,
    @SerializedName("Balance") var Balance: Double? = 0.0,
    @SerializedName("InvoiceItemDiscount") var InvoiceItemDiscount: Int? = 0,
    @SerializedName("InvoiceNetDiscountPerc") var InvoiceNetDiscountPerc: Double? = 0.0,
    @SerializedName("InvoiceNetDiscount") var InvoiceNetDiscount: Double? = 0.0,
    @SerializedName("InvoiceSubTotal") var InvoiceSubTotal: Double? = 0.0,
    @SerializedName("InvoiceTax") var InvoiceTax: Double? = 0.0,
    @SerializedName("InvoiceNetTotal") var InvoiceNetTotal: Double? = 0.0,
    @SerializedName("InvoiceRoundingAmount") var InvoiceRoundingAmount: Double? = 0.0,
    @SerializedName("OtherCharges") var OtherCharges: Int? = 0,
    @SerializedName("NetDiscount") var NetDiscount: Double? = 0.0,
    @SerializedName("InvoiceGrandTotal") var InvoiceGrandTotal: Double? = 0.0,
    @SerializedName("InvoiceTotalValue") var InvoiceTotalValue: Double? = 0.0,
    @SerializedName("InvoiceQty") var InvoiceQty: Int? = 0,
    @SerializedName("Remarks") var Remarks: String? = null,
    @SerializedName("CreditDays") var CreditDays: Int? = 0,
    @SerializedName("SalesOrderId") var SalesOrderId: String? = null,
    @SerializedName("Status") var Status: String? = "I",
    @SerializedName("TenantId") var TenantId: Int? = 0,
    @SerializedName("SalespersonId") var SalespersonId: Int? = null,
    @SerializedName("DeliveryPersonId") var DeliveryPersonId: Int? = null,
    @SerializedName("DeliveryPersonName") var DeliveryPersonName: String? = null,
    @SerializedName("SalesPersonName") var SalesPersonName: String? = null,
    @SerializedName("AmountInWords") var AmountInWords: String? = null,
    @SerializedName("PaymentTermId") var PaymentTermId: Int? = null,
    @SerializedName("BranchId") var BranchId: String? = null,
    @SerializedName("PaymentTermName") var PaymentTermName: String? = null,
    @SerializedName("FromLocationName") var FromLocationName: String? = null,
    @SerializedName("EmployeeName") var EmployeeName: String? = null,
    @SerializedName("TokenId") var TokenId: String? = null,
    @SerializedName("InvoiceDueDate") var InvoiceDueDate: String? = null,
    @SerializedName("Type") var Type: String? = "N",
    @SerializedName("ProfitMargin") var ProfitMargin: Int? = 0,
    @SerializedName("TaxName") var TaxName: String? = null,
    @SerializedName("Signature") var Signature: String? = null,
    @SerializedName("DeliveryOrderList") var DeliveryOrderList: ArrayList<String> = arrayListOf(),
    @SerializedName("DeliveryOrdered") var DeliveryOrdered: String? = null,
    @SerializedName("DeliveryOrderDate") var DeliveryOrderDate: String? = null,
    @SerializedName("DeliveryTimingId") var DeliveryTimingId: String? = null,
    @SerializedName("MemberId") var MemberId: String? = null,
    @SerializedName("VendorId") var VendorId: Int? = 0,
    @SerializedName("PaidAmount") var PaidAmount: Int? = 0,
    @SerializedName("CurrencyId") var CurrencyId: String? = null,
    @SerializedName("CurrencyRate") var CurrencyRate: Int? = 0,
    @SerializedName("ZatcaQRCode") var ZatcaQRCode: String? = null,
    @SerializedName("ThirdPartyId") var ThirdPartyId: String? = null,
    @SerializedName("AutoSync") var AutoSync: Boolean? = false,
    @SerializedName("IsDeleted") var IsDeleted: Boolean? = false,
    @SerializedName("DeleterUserId") var DeleterUserId: String? = null,
    @SerializedName("DeletionTime") var DeletionTime: String? = null,
    @SerializedName("LastModificationTime") var LastModificationTime: String? = null,
    @SerializedName("LastModifierUserId") var LastModifierUserId: String? = null,
    @SerializedName("CreationTime") var CreationTime: String? = null,
    @SerializedName("CreatorUserId") var CreatorUserId: Int? = null

)