package com.lfsolutions.retail.model.sale.invoice

import com.google.gson.annotations.SerializedName


data class SalesInvoice(

    @SerializedName("id") var id: String? = null,
    @SerializedName("invoiceNo") var invoiceNo: String? = null,
    @SerializedName("invoiceDate") var invoiceDate: String? = null,
    @SerializedName("poNo") var poNo: String? = null,
    @SerializedName("locationId") var locationId: Int? = null,
    @SerializedName("customerId") var customerId: String? = null,
    @SerializedName("customerName") var customerName: String? = null,
    @SerializedName("deliveryTimingDescription") var deliveryTimingDescription: String? = null,
    @SerializedName("customerRemarks") var customerRemarks: String? = null,
    @SerializedName("companyRemarks") var companyRemarks: String? = null,
    @SerializedName("balance") var balance: String? = null,
    @SerializedName("invoiceItemDiscount") var invoiceItemDiscount: String? = null,
    @SerializedName("invoiceNetDiscountPerc") var invoiceNetDiscountPerc: String? = null,
    @SerializedName("invoiceNetDiscount") var invoiceNetDiscount: Int? = null,
    @SerializedName("invoiceSubTotal") var invoiceSubTotal: String? = null,
    @SerializedName("invoiceTax") var invoiceTax: String? = null,
    @SerializedName("invoiceNetTotal") var invoiceNetTotal: String? = null,
    @SerializedName("invoiceRoundingAmount") var invoiceRoundingAmount: Int? = null,
    @SerializedName("otherCharges") var otherCharges: Int? = null,
    @SerializedName("netDiscount") var netDiscount: Int? = null,
    @SerializedName("invoiceGrandTotal") var invoiceGrandTotal: String? = null,
    @SerializedName("invoiceTotalValue") var invoiceTotalValue: String? = null,
    @SerializedName("remarks") var remarks: String? = null,
    @SerializedName("creditDays") var creditDays: Int? = null,
    @SerializedName("salesOrderId") var salesOrderId: String? = null,
    @SerializedName("status") var status: String? = null,
    @SerializedName("tenantId") var tenantId: Int? = null,
    @SerializedName("salespersonId") var salespersonId: Int? = null,
    @SerializedName("deliveryPersonId") var deliveryPersonId: String? = null,
    @SerializedName("deliveryPersonName") var deliveryPersonName: String? = null,
    @SerializedName("salesPersonName") var salesPersonName: String? = null,
    @SerializedName("amountInWords") var amountInWords: String? = null,
    @SerializedName("paymentTermId") var paymentTermId: String? = null,
    @SerializedName("branchId") var branchId: String? = null,
    @SerializedName("paymentTermName") var paymentTermName: String? = null,
    @SerializedName("fromLocationName") var fromLocationName: String? = null,
    @SerializedName("employeeName") var employeeName: String? = null,
    @SerializedName("tokenId") var tokenId: String? = null,
    @SerializedName("invoiceDueDate") var invoiceDueDate: String? = null,
    @SerializedName("type") var type: String? = null,
    @SerializedName("profitMargin") var profitMargin: Int? = null,
    @SerializedName("taxName") var taxName: String? = null,
    @SerializedName("signature") var signature: String? = null,
    @SerializedName("deliveryOrderList") var deliveryOrderList: String? = null,
    @SerializedName("deliveryOrdered") var deliveryOrdered: String? = null,
    @SerializedName("deliveryOrderDate") var deliveryOrderDate: String? = null,
    @SerializedName("deliveryTimingId") var deliveryTimingId: String? = null,
    @SerializedName("memberId") var memberId: String? = null,
    @SerializedName("vendorId") var vendorId: Int? = null,
    @SerializedName("paidAmount") var paidAmount: Int? = null,
    @SerializedName("currencyId") var currencyId: String? = null,
    @SerializedName("currencyRate") var currencyRate: Int? = null,
    @SerializedName("zatcaQRCode") var zatcaQRCode: String? = null,
    @SerializedName("thirdPartyId") var thirdPartyId: String? = null,
    @SerializedName("autoSync") var autoSync: Boolean? = null,
    @SerializedName("isDeleted") var isDeleted: Boolean? = null,
    @SerializedName("deleterUserId") var deleterUserId: String? = null,
    @SerializedName("deletionTime") var deletionTime: String? = null,
    @SerializedName("lastModificationTime") var lastModificationTime: String? = null,
    @SerializedName("lastModifierUserId") var lastModifierUserId: String? = null,
    @SerializedName("creationTime") var creationTime: String? = null,
    @SerializedName("creatorUserId") var creatorUserId: String? = null,
    @SerializedName("isDirectInvoice") var isDirectInvoice: Boolean? = null,
    @SerializedName("totalDiscountAmount") var totalDiscountAmount: Int? = null,
    @SerializedName("totalShipmentCharges") var totalShipmentCharges: Int? = null,
    @SerializedName("roundedAmount") var roundedAmount: Int? = null,
    @SerializedName("localTotal") var localTotal: String? = null,
    @SerializedName("isFoc") var isFoc: Boolean? = null,
    @SerializedName("DeliveryOrderList") var DeliveryOrderList: ArrayList<String> = arrayListOf()

)