package com.lfsolutions.retail.ui.delivery.order

data class DeliveryOrder(
    var creationTime: String? = null,
    var creatorUserId: Int? = null,
    var currencyId: Int? = null,
    var currencyRate: Int? = 0,
    var customerId: Int? = null,
    var customerName: String? = null,
    var deleterUserId: Int? = null,
    var deletionTime: String? = null,
    var deliveryDate: String? = null,
    var deliveryNo: Int? = null,
    var deliveryPersonId: String? = null,
    var deliveryTimingId: String? = null,
    var erpInternalId: Int? = null,
    var id: Int? = null,
    var isCancelled: Boolean? = null,
    var isDeleted: Boolean? = null,
    var isFoc: Boolean? = false,
    var lastModificationTime: String? = null,
    var lastModifierUserId: Int? = null,
    var locationId: Int? = null,
    var salesPersonId: Int? = null,
    var memberId: Int? = null,
    var paidAmount: Double? = 0.0,
    var poOtherCharges: Double? = 0.0,
    var poRoundingAmount: Double? = 0.0,
    var referenceNo: String? = null,
    var remarks: String? = null,
    var salesInvoiceId: Int? = null,
    var salesOrderId: Int? = null,
    var soNetDiscount: Double? = 0.0,
    var status: String? = "R",
    var tenantId: Int? = 0,
    var totalDeliveredQty: Double? = null,
    var totalQty: Double? = 0.0,
    var signature: String? = null,
    var subTotal: Double? = null
)